# **CIS 520: Machine Learning**
## **Array Practice**


- **Content Creators:** Pengrui Wang, Siyun Hu, Ani Cowlagi
- **Content Reviewers:** Lyle Ungar
- **Objectives:** This is self-practice for performing useful manipulations on numpy arrays.

If you are not familiar with NumPy, feel free to refer to the [NumPy Tutorial](https://github.com/ageron/handson-ml/blob/master/tools_numpy.ipynb) and the [Vectorization Notebook](https://drive.google.com/file/d/1xB3A11G0Bq2sN7EMmLiAPS-DXhoGK92Q/view?usp=sharing).


In [ ]:
#@markdown Tell us your thoughts about what you want to learn.
thoughts = '' #@param {type:"string"}
import time
try: t0;
except NameError: t0=time.time()

## **Autograding and the PennGrader**

As usual, you'll need to set up the PennGrader!

Enter your PennID (numbers not letters!) in the specified section.

### Imports and Setup

Run but do not modify these cells!

In [ ]:
%%capture
!pip install penngrader


In [ ]:
import random 
import numpy as np
import pandas as pd
import os
import sys
import matplotlib.pyplot as plt
from numpy.linalg import *

import dill
import base64

In [ ]:
# For autograder only, do not modify this cell. 
# True for Google Colab, False for autograder
NOTEBOOK = (os.getenv('IS_AUTOGRADER') is None)
if NOTEBOOK:
    print("[INFO, OK] Google Colab.")
else:
    print("[INFO, OK] Autograder.")
    sys.exit()

[INFO, OK] Google Colab.


### Insert PennID here!

In [ ]:
#PLEASE ENSURE YOUR PENN-ID IS ENTERED CORRECTLY. IF NOT, THE AUTOGRADER WON'T KNOW
#TO ASSIGN POINTS TO YOU IN OUR BACKEND
STUDENT_ID = 99999999 # YOUR PENN-ID GOES HERE AS AN INTEGER#

In [ ]:
import penngrader.grader

grader = penngrader.grader.PennGrader(homework_id = 'CIS_5200_202230_HW_Array_Practice_WS', student_id = STUDENT_ID)

PennGrader initialized with Student ID: 99999999

Make sure this correct or we will not be able to store your grade


In [ ]:
# A helper function for grading utils
def grader_serialize(obj):        # A helper function
    '''Dill serializes Python object into a UTF-8 string'''
    byte_serialized = dill.dumps(obj, recurse = True)
    return base64.b64encode(byte_serialized).decode("utf-8")

## **Questions**

In [ ]:
# run this first to set up
import numpy as np

**Question 1: How to stack two arrays vertically?**


In [ ]:
# Input:
a = np.arange(100).reshape(2,-1)
b = np.repeat(1, 100).reshape(2,-1)

# Output: Stack array a and b vertically
# E.g.
#> a = array([[0, 1, 2, 3, 4]
#>            [5, 6, 7, 8, 9]])
#> b = array([[1, 1, 1, 1, 1]
#>            [1, 1, 1, 1, 1]])
#> out = array([[0, 1, 2, 3, 4],
#>              [5, 6, 7, 8, 9],
#>              [1, 1, 1, 1, 1],
#>              [1, 1, 1, 1, 1]])

out =  # Fill in here    

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_stack', answer = (a, b, out))

**Question 2: How to swap two columns in a numpy array?**


In [ ]:
# Input:
arr = np.arange(121).reshape(11,11)
print(arr)

# Output: Swap columns 1 and 2 in the array arr IN-PLACE.
# That is, modify arr directly, do not make any new arrays

# Write code here

print(arr)

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_swap', answer = arr)

**Question 3: How to rank items in an array?**

In [ ]:
# Input:
np.random.seed(19)
arr = np.random.randint(100, size=1000)

# Output: sort the array in increasing order, output the sorted indices (not values)
# as a numpy array
out =       # Fill in here

print(out)

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_argsort', answer = (arr, out))

**Question 4: How to find the maximum value in each row of a 2D numpy array?**

In [ ]:
np.random.seed(17)
arr = np.random.randint(1,10, [15,8])
print(arr)

# Output: Compute the maximum value of each row in the array arr. Flatten the resut as a 1D numpy array.
row_maxes =             # Fill this in

print(row_maxes)

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_rowmax', answer = (arr, row_maxes))

**Question 5: Slice a 2D numpy array**

In [ ]:
# Input:
arr = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

# Output: Slice the array arr to get the following result
# [[17 18]
#  [22 23]
#  [27 28]]

sliced =                  # Fill this in

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_slice', answer = (arr, sliced))

**Question 6: Transpose and product**

In [ ]:
# Input:
a = np.array([[1, 0], [0, 1], [4, 7]])
b = np.array([[4, 1], [2, 2], [49, 17]])

# Output: compute the product of a^T and b (a 2x2 matrix)

trans_prod =             # Fill in here


Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_trans_prod', answer = (a, b, trans_prod))

**Question 7: Element-wise product**

In [ ]:
# Input: 
a = np.array([[1, 0], [0, 1], [4, 7]])
b = np.array([[4, 1], [2, 2], [49, 17]])

# Output: compute the element-wise product of a and b (a 3 x 2 matrix)

elt_wise =             # Fill this in

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_eltwise', answer = (a, b, elt_wise))

**Question 8: Assign values to an array**



In [ ]:
# Input:
x = np.arange(8)
arr = np.arange(100)

# Output: assign the values in array x to the last elements in the array arr (in the exact same order as the elements appear in x). 
# E.g. arr_orig = [0, 1, 2, 3, 4, 5, 6, 7], x = [0, 1, 2, 3] --> arr = [0, 1, 2, 3, 0, 1, 2, 3]
# Note: do not use any loops to achieve this. 

# Update arr here


Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_assign_values', answer = (x, arr))

Follow up Question: This is a bit tricky! Take a look at the following code. 

```
x = np.arange(0, 50, 10)
x[np.array([1, 1, 3, 1])] += 1
```

What will the value of x be at the end? 

*   Option 1: [ 0, 11, 20, 31, 40]
*   Option 2: [ 0, 13, 20, 31, 40]
*   Option 3: IndexError: index is out of bounds for axis 0 with size 5
*   Option 4: I don't know!!! :(





Submit to Autograder

In [ ]:
choice = ""     # Type in Option 1, Option 2, Option 3, Option 4

grader.grade(test_case_id = 'test_case_select_increment', answer = choice)

**Question 9: A challenging quesiton. Replace all None values with the mean of all other elements. (We will later cover this as "imputation")**

*Note: you should be able to do it without using any for/while loop.* 


In [ ]:
# Input:
arr = np.array([[16,  7, 23, None, 46, 23, 32, 69],
       [40, 85, 45,  None,  2, 18, 42, 57],
       [11, 99,  4, 64,  7, 92, 39, 92],
       [42, 58, None, 18, 50, 33, 62,  6],
       [39,  3, 45, 55, 14, 57, 28, None]])


In [ ]:
arr

array([[16, 7, 23, None, 46, 23, 32, 69],
       [40, 85, 45, None, 2, 18, 42, 57],
       [11, 99, 4, 64, 7, 92, 39, 92],
       [42, 58, None, 18, 50, 33, 62, 6],
       [39, 3, 45, 55, 14, 57, 28, None]], dtype=object)

In [ ]:
arr1 =  # Replace the instances of None in arr with np.nan. Hint: Consider using np.where

In [ ]:
arr1

array([[16, 7, 23, nan, 46, 23, 32, 69],
       [40, 85, 45, nan, 2, 18, 42, 57],
       [11, 99, 4, 64, 7, 92, 39, 92],
       [42, 58, nan, 18, 50, 33, 62, 6],
       [39, 3, 45, 55, 14, 57, 28, nan]], dtype=object)

In [ ]:
arr1 = arr1.astype(float)

# Replace the np.nan elements in arr1 with the mean of non nan elements in arr1
# Hint: Consider using np.isnan and np.nanmean



In [ ]:
arr1

Submit to Autograder

In [ ]:
grader.grade(test_case_id = 'test_case_replace_nan', answer = (arr, arr1))

## **Submitting to the Autograder**

Now go to the File menu and choose "Download .ipynb".  Go to [Gradescope](https://www.gradescope.com/courses/409970) and:

1. From "File" --> Download both .ipynb and .py files
1. Name these files `Array_Practice_WS.ipynb` and `Array_Practice_WS.py` respectively
1. Sign in using your Penn email address (if you are a SEAS student we recommend using the Google login) and ensure  your class is "CIS 5200"
1. Select **Worksheet: Array Practice**
1. Upload both files
1. PLEASE CHECK THE AUTOGRADER OUTPUT TO ENSURE YOUR SUBMISSION IS PROCESSED CORRECTLY!

You should be set! Note that this assignment has 10 autograded points that will show up upon submission. Points are awarded based on a combination of correctness and sufficient effort. 